Repository onpointvn/tiktok_shop_ex, pull requests merged in 2022-07, with the labels that each got.

#38 Hotfix/add confirming ready to ship for a fulfillment
  .formatter.exs
  lib/api/fulfillment.ex
  lib/api/order.ex
Labels: hotfix, master

#39 Hotfix/add confirming ready to ship for a fulfillment
  .formatter.exs
  lib/api/fulfillment.ex
  lib/api/order.ex
  mix.exs
Labels: develop

#40 Bump version 0.2.1
  CHANGELOG.md
  VERSION
Labels: master
